### PR TITLE
make streamie compatible with socket.io v0.7

### PR DESCRIPTION
**Pull request by badboy**
This needs an update of the locally installed socket.io version, too.

It uses the built-in delivered socket.io-client lib. This may cost you some traffic. If this is not okay, tell me and I will add the socket.io-client back in as a submodule.

Another thing: I configured my editor to remove all trailing whitespace. Therefore I have another commit removing these in all *.js files. If you want this included, please tell me.

### CODE REVIEW

**Comment by cramforce** [comment]
I'd really like to make Streamie compatible with node 0.4 or 0.5. Unfortunately my last attempt ended in dependency hell because many dependencies do not yet work with npm 1.0

**Comment by cramforce** [comment]
Trailing white-space away = Great!

**Comment by badboy** [comment]
I had no problems running streamie locally using node.js `v0.4.9` after running

```
npm install socket.io@latest oauth@latest node-static@latest nstore@latest http-proxy@latest less@latest
```

**Comment by cramforce** [comment]
Interesting. I'd really like to upgrade more dependencies, though, of which not all work with a new npm which you need to run under 0.4.
Actually I'd like to commit all dependencies as "fake submodules" directly into streamie, so that npm is no longer neccessary for simple usage.

**Pull request closed without merging**
