### PR TITLE
use stream.twitter.com instead of betastream.twitter.com

### PR DESCRIPTION
**Pull request by amrnt**
After the stability of stream.twitter.com

### CODE REVIEW

**Comment by cramforce** [comment]
Are you sure about this? Did you test it?

I dont think user streams are on the stable stream yet. Do you know somebody with twitter to check?

**Comment by amrnt** [comment]
http://dev.twitter.com/pages/user_streams#ImportantItems
See the second and the third point.

**Comment by cramforce** [comment]
I know about this. Site Streams do not support user streams yet, so there is no way yet to switch. Twitter will get in touch with me as soon as site streams are mature enough to support Streamoe

**Comment by cramforce** [comment]
Switched to real production user stream userstream.twitter.com

**Pull request closed without merging**
