### PR TITLE
autotranslation

### PR DESCRIPTION
**Pull request by jeromeetienne**
To get autotranslation needed some modifications in setting + streamplugin processing too. here is the list of the modification. what do you think ?
- setting has been modified to support { 'en': 'english', 'fr':'french'} values
  - needed to get prefered language selection
- helper refactored
  - some streamplugin htmlEncode got in helpers.js
  - bug fix on forgeting single quote
  - needed to get htmlDecode on google translate output
- stream reprocess
  - did the mechanism to reprocess and replace an existing tweet
  - needed to get async behaviour.
  - aka i get the tweet, get the translation, and then reprocess+replace the tweet by the translated one
- google translate in stream plugins

### CODE REVIEW

**Comment by cramforce** [comment]
Hi, I love the settings stuff. This was the plan all along but I way to lazy to implement it :)

I'm not sure doing htmlEncode(htmlDecode(text)) on tweets is correct. I didnt find a spec on this. If you just tweet &quot; it will come through just like that and would end up as " with that scheme.

Looks good overall. Could you remove the _s in favor of cameCase?

Thanks!
Malte

**Comment by jeromeetienne** [comment]
Hi, 

ok I removed all the _'s i found, just a habit i guess. 

About the htmlEncode stream plugins
- current behavior is the same before
- http://github.com/cramforce/streamie/blob/master/public/lib/stream/streamplugins.js#L200-208 is already doing a htmlEncode(htmlDecode(text)). 
- I just put htmlDecode from streamplugin.js to helper.js (and added the missing single quote). 
- i think it is cleaner this way and i needed htmlDecode to process google translate output.

do you see any additional changes to make ?

**Comment by jeromeetienne** [comment]
any news on this one ? or it got swamp in jsconf party ? :)

**Comment by cramforce** [comment]
Hey, I'm going to include it. Please merge your branch up to cramforce/master first

**Comment by jeromeetienne** [comment]
cool. merged with master

**Comment by cramforce** [comment]
Please push that :)

**Comment by jeromeetienne** [comment]
duh. my bad. :)

**Pull request merged**
