### PR TITLE
Chrome Notifications

### PR DESCRIPTION
**Pull request by kosta**
- Displays Chrome Notifications whenever a new tweet comes in (except: previously seen tweets and "prefill" tweets)
- Must be enabled in settings (only shown in settings when browser supports notifications)
- added function settings.setGui(), as gui needs to react when user e.g. denies right to show notifications

If you accept this, it will be my first open-source patch to be accepted > 3 lines :)

### CODE REVIEW

**Comment by cramforce** [comment]
Hi,

thank you, looks good. Would you mind removing the "closing block" comments and instead add some more general comments.

Could it be that in the notify-Plugin (which maybe should be called webkitNotify) the this() isnt called sometimes?

Bye
Malte

**Comment by kosta** [comment]
- removed "closing block" comments just for you :)
- MOAR! comments (did I overdo it?)
- changed "notify" to "webkitNotify", "registerNotifications" to "registerWebkitNotifications" and the setting "notifications.chrome-notifications" to "notifications.enableWebkitNotifications"
- about this() not being called: 
  After reading the code thoroughly, I am convinced that this() should always be called. The functions looks something like this:
  
  ```
    if (!tweet.seenBefore && 
      !tweet.prefill &&
      plugin.current < 5 &&
      window.webkitNotifications && 
      window.webkitNotifications.checkPermission() == 0 &&
      settings.get('notifications', 'enableWebkitNotifications')) {
      try {
        //whatever...
      } catch(e) {
        //maybe I should log something here?
      }
    }
    this();
  ```

assuming that tweet, plugin, window and settings are objects, and settings.get() doesn't throw anything (It shouldn't as I registered the setting, right?), "this()" should always be called.

registering the settings looks like this (in initplugins):

```
    if (window.webkitNotifications) {
      //only register settings if browser allows that
      settings.registerKey('notifications', 'enableWebkitNotifications', 'Chrome notifications',
        permission === 0, [true, false]);
```

So of course everythings possible, especially when I'm writing code :) but it would rather surprise me if this() was not called...

**Comment by cramforce** [comment]
I made some more changes in
http://github.com/cramforce/streamie/commit/538d31c38bc08535987d4cf45b610c8187df3469

Please check whether they are cool with you

**Comment by kosta** [comment]
- merged my "settings return null" branch
- merged your current master HEAD

**Comment by kosta** [comment]
merged your branch 'kosta' (you removed setGui and redraw settings panel on every settings change)

**Comment by cramforce** [comment]
Merged

**Pull request merged**
